name: Build and Push to ECR

on:
  push:
    branches: ["feature/aws-ec2-cicd"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build & Push Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}
          GIT_SHA=$(git rev-parse --short HEAD)

          docker buildx build \
            --platform linux/amd64 \
            --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            --build-arg AWS_REGION=$AWS_REGION \
            --build-arg DATABASE_URL=$DATABASE_URL \
            --build-arg S3_BUCKET_NAME=$S3_BUCKET_NAME \
            -t $IMAGE_URI:$GIT_SHA \
            -t $IMAGE_URI:latest \
            --push .
